[package]
name = "pragma"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
logos = "0.14.0"
paste = "1.0.14"
smol_str = "0.2.2"
bitflags = "2.5.0"
serde = { version = "1.0.202", features = ["derive"] }
